### PR TITLE
Tweaks to get import successfully running again.

### PR DESCRIPTION
**Pull request by bseeger**
The fix that @acoburn pointed out in [PR 19](https://github.com/fcrepo4-labs/fcrepo-import-export-verify/pull/19)  had me revisit import and I noticed that it wasn't running correctly.  This addresses the issues I found and now both import and export run successfully.

### CODE REVIEW

**Comment by jwestgard** [comment]
I wanted to merge this PR, but I noticed that the Travis build is failing. Travis is new to me so I don't know what it is checking or how to deal with the failure. Thoughts?

**Comment by acoburn** [comment]
@jwestgard travis is only doing a style check with `flake8` and executing the script with`-h`. I suspect the failure is related to the AWS outages yesterday, since running those manually seemed fine. (That said, there may be some additional things to do to make travis happy).

**Comment by jwestgard** [comment]
Thanks, @acoburn. Since the Travis site cannot retrieve the log or provide futher information, I would be inclined to merge this PR, and just keep an eye out for problems in the future.  What do you think, @bseeger?

**Comment by bseeger** [comment]
@jwestgard  - what you suggest sounds good to me.   I can't imagine there's a problem with this script.  I ran it through flake8 before I committed, so it should be PEP 8 compliant.

**Pull request merged**
