### PR TITLE
FCREPO-2486 & 2492

### PR DESCRIPTION
**Pull request by jwestgard**
- resolves both original bug report (FCREPO-2486) and feature ticket (FCREPO-2492)
- when "no binaries" option is chosen, filters out triples that have binaries as their object
- adds a method for comparing graphs loosely (i.e. untyped literals are treated the same as explicitly typed string literals for comparison purposes)
- this 'relaxed_compare' method is not currently used by the tool since import-export no longer produces turtle with untyped string literals (instead following the older turtle 1.0 rule where string literals are always typed), but the method is made available for future use should it become necessary
- finally, lays some groundwork for legacyMode support (FCREPO-2493) but that issue is not fully resolved here.
- NOTE: when no binaries are exported, the tool is quite a bit slower than with binaries; ways to improve performance should be looked at going forward.

### CODE REVIEW

**Comment by dbernstein** [comment]
I just gave this a try.   I created a container with one container and one binary.
I then exported using the following command line: 
 java -jar fcrepo-import-export-0.1.1-SNAPSHOT.jar -d export -a -m export -r http://localhost:8686/f4/rest --writeConfig export-config.yml 
On verification  there was one failure with the following stack trace:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/verifier.py", line 135, in execute
    original.filter_binary_refs()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/resources.py", line 98, in filter_binary_refs
    FedoraResource(o, self.config, self.logger).is_binary():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/resources.py", line 56, in __init__
    self.console.error("Unexpected response from Fedora")
AttributeError: 'FedoraResource' object has no attribute 'console'

**Review by dbernstein — APPROVED** [review]
This all looks good.

**Comment by dbernstein** [comment]
The code looks okay to me,  but I'll wait on your feedback regarding the failure I was seeing.

**Review by dbernstein — CHANGES_REQUESTED** [review]
Just reworking the review - I should have left the comment with a request for changes here.  
**********************
I just gave this a try. I created a container with one container and one binary.
I then exported using the following command line:
java -jar fcrepo-import-export-0.1.1-SNAPSHOT.jar -d export -a -m export -r http://localhost:8686/f4/rest --writeConfig export-config.yml
On verification there was one failure with the following stack trace:

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/verifier.py", line 135, in execute
original.filter_binary_refs()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/resources.py", line 98, in filter_binary_refs
FedoraResource(o, self.config, self.logger).is_binary():
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcrepo_verify/resources.py", line 56, in init
self.console.error("Unexpected response from Fedora")
AttributeError: 'FedoraResource' object has no attribute 'console'

Looks like there are two issues: One is the error coming from Fedora. The second is a preexisting bug related to the non-existent self.console property. I'll create bug report for the latter.

**Comment by jwestgard** [comment]
I think I fixed this problem, but I have been unable to test it.  It would seem to require getting Fedora to return something other than a 200, 307, 401, 404, or 405 response, which is not a normal situation.  I thought I could test it on an import, but now I'm running into the problem with server-managed triples again.  Do you have an idea how to test this?

**Comment by dbernstein** [comment]
@jwestgard : I believe problem seems to be at line 52 of resources.py.   The response that is coming back is a 405 error. However the line doesn't check for 405s.

**Comment by dbernstein** [comment]
If you add handling for the 405 you should be good to go.

**Comment by jwestgard** [comment]
Thanks. I see you've already got the PR to fix the loggers.console bit. I can test that fix now--I managed to devise a scenario that produces the requisite response from Fedora to trigger that section of code. I'll also add in the 405 handling.

**Comment by dbernstein** [comment]
@jwestgard :  what is the status of the pull request?  I haven't seen new mods since your comment on Friday.  Let me know if I'm missing something or if I can help in anyway.

**Comment by jwestgard** [comment]
Thanks, @dbernstein. You're not missing anything. I am just slow. :-) Actually, busy right now, but will get to this next week.

**Comment by dbernstein** [comment]
@jwestgard :  is there something I can do to help move this along?  If you're plate if full,  I can pick up where you leave off.  It would be good to wrap this up before it gets too stale.  Let me know.

**Review by dbernstein — APPROVED** [review]

**Pull request merged**
