### PR TITLE
FCREPO-2457: handle failed connection gracefully

### PR DESCRIPTION
**Pull request by jwestgard**
- Creates a repository class that can be used to collect behaviors relating to a Fedora.
- Creates an instance of that class based on configuration at runtime.
- Checks connection to the repository and fails gracefully if no connection.

### CODE REVIEW

**Comment by awoods** [comment]
@dbernstein : Thanks for moving things forward. 
Two comments:
1. When you do a squash/merge, please manually clean-up the commit message... also ending with a statement along the lines of: `Resolves: <link-to-jira-ticket>`
2. Close the JIRA ticket with a comment that says: `Resolved by: <link-to-github-commit>`

**Comment by jwestgard** [comment]
dbernstein: agreed unit tests would be good. I would probably need your help to get started there since I don't have a lot of experience with automated tests.

**Comment by dbernstein** [comment]
@awoods 👍

**Comment by dbernstein** [comment]
@jwestgard :  okay - I've just begun to add tests myself (I'm not so experienced with writing tests in python).  Keep an eye on the tests/ dir for examples.

**Pull request merged**
