### PR TITLE
Breaks up verify.py into smaller more focused modules.

### PR DESCRIPTION
**Pull request by dbernstein**
Resolves: https://jira.duraspace.org/browse/FCREPO-2451

### CODE REVIEW

**Comment by jwestgard** [comment]
Everything installs and runs for me.  I think that the commenting can probably be cleaned up some, now that we're in separate files (header divisions aren't really needed anymore).  But that can probably be a separate PR.

**Comment by jwestgard** [comment]
I wonder about the name "model.py". Right now that just has the class for interpreting the import-export config file.  I think we should consider adding a repository class to manage fedora repository instances and this seems like the logical place to put that.  If this module has configuration and repository classes, is model.py the right name?

**Comment by jwestgard** [comment]
Looks good otherwise.

**Comment by dbernstein** [comment]
I say let's move forward as is.  I'm open to changing model.py to something else, but I suggest we wait until I've pushed up all my changes and you can see where things stand.   If you can do the squash and merge, then I'll push my last PR and we can discuss name / documentation changes.

**Pull request merged**
