### PR TITLE
Handle import-export batches with no binaries

### PR DESCRIPTION
**Pull request by jwestgard**
If the -b (binaries) option has not been invoked upon import/export, the non-rdf and fcr:metadata resources will not be included in the batch.  This commit causes the verification tool to skip such resources when iterating over the original resource tree.

It also sets the config.bin attribute to False by default. This value gets overidden if the -b flag is present in the importexport.config file.

Fixes https://jira.duraspace.org/browse/FCREPO-2342

### CODE REVIEW

**Comment by jwestgard** [comment]
@ruebot : was the meaning of the -b option discussed during the creation of the import-export tool?  I cannot remember this coming up, but I was surprised to see that the import-export also skips over fcr:metadata resources if -b is not invoked.  I consider those to be rdf descriptions and sort of feel like as a repository manager if I'm doing a dump of my metadata, I would want those to come along.

**Comment by escowles** [comment]
@ruebot I don't remember that issue being discussed — but I agree with @jwestgard that exporting the binary descriptions seems like a good idea.

**Comment by jwestgard** [comment]
Others who are able to read Java code should confirm, but in my testing of exports with no -b, fcr:metadata did not come along.  

On the other hand, it could introduce some complication for import perhaps.  If fcr:metadata resources are there on disk, but no binaries are there, would Fedora accept them?  I guess this is something that should be brought to all stakeholders for feedback.

This PR handles the existing behavior, so I think can still be merged as is, once it is tested of course.

**Comment by jwestgard** [comment]
@ruebot, I can write a ticket if that makes sense.  Or should we bring it up for discussion first on IRC or elsewhere?

**Comment by bseeger** [comment]
I'll check later today or Monday if the camel serialization tool exports the fcr:metadata fro binaries.  Just thought it might be a good data point for comparison.

**Comment by jwestgard** [comment]
Thanks @ruebot. I guess I failed to recognize that this PR would also depend on the previous PR (#10), so probably should have been made against that?  Some of the best practices are fuzzy to me.

**Comment by jwestgard** [comment]
@ruebot, if you want me to "rebase" or what have you against the current code and resubmit the PR I can do that, but not until later this PM.

**Pull request merged**
