### PR TITLE
Refactor Logging feature (FCREPO-2368)

### PR DESCRIPTION
**Pull request by jwestgard**
The logger has been completely refactored to be more verbose in order to support easier debugging. This refactoring includes the following changes:

- removes the -v/--verbose and -l/--log options (logging always happens now)
- adds the -q/--quiet option
- defines -l/--level to handle logging level

By default logging level is INFO and the output goes to screen.  With -q chosen, summary output goes to screen, and logging goes to the file at log/YYYYMMDD-HHMM.log.  Default log level is INFO, but by setting logging to DEBUG one can get even more detailed information useful in tracking down the source of unexpected discrepancies when checking resources. Level WARNING reports only resource mismatches and errors.  Level ERROR is not very useful since it only reports script errors that should normally not occur.

These changes are significant, but I believe the result will better meet our use cases, in particular providing for much easier troubleshooting when there are problems in the verification tool. I'd be happy to discuss the changes if there are questions.

### CODE REVIEW

**Comment by bseeger** [comment]
I'll check it out in the am, but I'm curious in the mean time - where folks asking for a reversal/change of the logging semantics?

**Comment by jwestgard** [comment]
That's a fair question. They weren't asking for changes so much as I was noticing that we really need fuller log information, since there are a lot of reasons why a check of a particular resource can fail, and very rarely does that have anything to do with a problem in import/export.

Changing around the controls was motivated by aligning the tool's behavior more closely to the import/export tool itself (with log information going to screen by default), and also making it easier to run multiple tests without needing to resort to naming each one: "log2", "log3", "log4".  But this part of the PR is really just a proposal and could be reversed.

**Comment by bseeger** [comment]
You should update the readme as well, with the config changes.

**Comment by bseeger** [comment]
This assumes that I have a logs directory in place:  
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/bseeger/Projects/fedora/test_fedora/fcrepo-import-export-verify/logs/20161219-1045.log'`

**Comment by bseeger** [comment]
So here are my thoughts - I just plain wouldn't use this tool w/o the `-q` flag running. That's way too much output for me to even find it useful, while streaming past.  (I find the same for the import/export tool - I pay almost no attention to the output of it since it's so verbose). I don't know what the popular paradigm is, but I always operate on the idea of giving a minimum amount of useful data and allowing the user to ask for more via flags.  That way they get a summary, and if they want to see information on each resource, they can ask for more.  The idea being that by default you only see information about the errors that occur; should you need to debug you can ask for more output.  @whikloj  - what do you think?

**Comment by jwestgard** [comment]
I agree with you, but I also have been finding that my personal preferences are often considered rather old fashioned and passé in modern software development, so was trying to do what I thought was up-to-date... :-)

We could keep -v, and change it back to how you originally had done it, i.e. with -v sending logs to screen, and make the current behavior of -q the default.  I do think it makes sense to make logging  automatic, since unless it runs completely without errors, inevitably users are going to want the log info. We might even consider making DEBUG-level logging the default since it would just go to a file unless specified otherwise.  But I'm OK with whatever we can determine the user community to want...

**Comment by bseeger** [comment]
@jwestgard - I do like the idea of the log always being written to. 

@ruebot, @awoods  - do you have any opinions on this PR?

**Comment by awoods** [comment]
I have not done a code-level review of this PR, but I completely agree with these [comments](https://github.com/fcrepo4-labs/fcrepo-import-export-verify/pull/18#issuecomment-268006085).

**Comment by jwestgard** [comment]
While we await more possible feedback, since we all seem to be in agreement on a few adjustments, I can try to implement the changes outlined above in a new commit added to this PR (i.e. making logging to file the default, with a -v option for folks who want to have the logs go to stdout, also update the readme file).

**Pull request closed without merging**
