### PR TITLE
Verifies exported external content.

### PR DESCRIPTION
**Pull request by dbernstein**
Resolves: https://jira.duraspace.org/browse/FCREPO-2471

See comment on  https://jira.duraspace.org/browse/FCREPO-2471 for testing instructions.

### CODE REVIEW

**Comment by jwestgard** [comment]
@dbernstein, @awoods: what is your understanding of this requirement?  Should verification only happen on export (i.e. the local copy is checked against the binary stored ouside of Fedora)?  I have tested this on import and am seeing SHA1 mismatches because external was set to false, and upon import it is comparing the empty binary on disk to the externally stored file.

**Comment by dbernstein** [comment]
@jwestgard: hmmm.  So yes,  I would expect on import verification, the verifier tool would skip verification of external resources. @awoods :  what's your thought?

**Comment by dbernstein** [comment]
@jwestgard: BTW I did not test the import so I'm not surprised you're seeing an issue.  Good catch.

**Comment by jwestgard** [comment]
Verification of export with external binaries works fine.  Verification of import also works for binary resources, assuming external was set to true.

So my inclination would be to go ahead and merge this as is, and create a separate ticket for ignoring the ".external" resources that are created on disk on export when external is set to false.  Subsequent import verification should simply skip over those resources.  Let's give @awoods a chace to weigh in though.

**Pull request merged**
